### ISSUE TITLE
Numeric decimals being converted into Decimal() objects

### ISSUE THREAD

**Issue by mittenchops** [isagalaev/ijson#13]
I'm reading from a geographic shapefile that has, among other data types, a list of coordinates, such as...

```
{
  "type": "FeatureCollection",
  "features": [
{
  "geometry": {
    "type": "Polygon", 
    "coordinates": [
      [
        [
          -123.09098499999993, 
          45.77992400000005
        ], 
```

The coordinates are getting converted in ijson into:

```
[Decimal('-123.09098499999993), Decimal('45.77992400000005')]
```

I'm not sure whether this is a bug or a feature, but it's making my database choke.  =)

My ijson loader looks like this:

```
def loader(shapefile, collection):
    jf = open(shapefile)
    data = ijson.items(jf,'features')
    for d in data:
        try:
            db[collection].insert(d)
        except:
            pass
```

My vanilla loader, without ijson, looked like this (and worked, but not on the large files I need ijson for)

```
def loader(shapefile, collection):
    jf = open(shapefile)
    data = json.load(jf)
    for d in data['features']:
        db[collection].insert(d)
```

My database is complaining about the Decimal() objects.  Where would I add something to convert only the Decimal() objects into their numeric values?

**Comment by asavpatel92** [comment]
@mittenchops currently I am having same problem... I am new to ijson can you guide me where do I need to make changes??? my db only supports int values so I probably will have to convert all values to string and then insert it into db.

**Comment by SalomonSmeke** [comment]
I wanted to add what landed on the codebase I'm working on so that this isn't an arduous read for anyone in the future:

```python
def floaten(iter_ijson_parser):
    """Ensure numeric events are Float and not Decimal by filtering a ijson event stream.

    Args:
        iter_ijson_parser: ijson event stream.

    Returns:
        generator: ijson event stream.
    """
    for prefix, event, value in iter_json_parser:
        if event == 'number' and isinstance(value, Decimal):
            value = float(value)
        yield prefix, event, value```

Usage:

```python
   for prefix, event, value in floaten(ijson.parse(<str>)):
      # do stuff
      pass
```

**Comment by etos** [comment]
simplejson / ujson will dump Decimals as floats

**Comment by chrisengelsma** [comment]
For the Googlers:

There's a detailed explanation on [how to get this to work on the MongoDB API website](https://api.mongodb.com/python/current/examples/custom_type.html), but to summarize:

You have to create a code that converts between BSON's Decimal128 type and Python's Decimal type. Here's what to do:

Import these:
```python 
from decimal import Decimal
from bson.codec_options import CodecOptions, TypeRegistry, TypeCodec
from bson.decimal128 import Decimal128
```

Create this class:

```python
class DecimalCodec(TypeCodec):
    python_type = Decimal   # the Python type acted upon by this type codec
    bson_type = Decimal128  # the BSON type acted upon by this type codec

    def transform_python(self, value):
        return Decimal128(value)

    def transform_bson(self, value):
        return value.to_decimal()
```

Create your codec options:
```python
decimal_codec = DecimalCodec()
type_registry = TypeRegistry([decimal_codec])
codec_options = CodecOptions(type_registry=type_registry)
```

Pass `codec_options` in when you get your collection:

```python
coll = db.get_collection("my_collection", codec_options=codec_options)
```

Done.

**Comment by SalomonSmeke** [comment]
@chrisengelsma orrrrr fork ijson and change Decimal to Float!
