### ISSUE TITLE
Python3 compatibility issue

### ISSUE THREAD

**Issue by acrisci** [isagalaev/ijson#30]
Running this very simple example with python3:

```python
import ijson

parser = ijson.parse(open('./tree.json'))

for prefix, event, value in parser:
    print(prefix)
    print(event)
    print(value)
```

Gives this error:

```
Traceback (most recent call last):
  File "ij.py", line 6, in <module>
    for prefix, event, value in parser:
  File "/usr/lib/python3.4/site-packages/ijson/common.py", line 58, in parse
    for event, value in basic_events:
  File "/usr/lib/python3.4/site-packages/ijson/backends/python.py", line 178, in basic_parse
    for value in parse_value(lexer):
  File "/usr/lib/python3.4/site-packages/ijson/backends/python.py", line 107, in parse_value
    pos, symbol = next(lexer)
  File "/usr/lib/python3.4/site-packages/ijson/backends/python.py", line 26, in Lexer
    buf = f.read(buf_size)
  File "/usr/lib/python3.4/codecs.py", line 493, in read
    data = self.bytebuffer + newdata
TypeError: can't concat bytes to str
```

It works just fine with Python 2.

**Comment by acrisci** [comment]
I get the error even when the contents of the json file is very simple, such as `{"test": "ok"}`.

**Comment by acrisci** [comment]
I got it to work by opening the file as bytes:

```python
import ijson

parser = ijson.parse(open('./tree.json', 'rb'))

for prefix, event, value in parser:
    print(prefix)
    print(event)
    print(value)
```

Maybe there should be a check that the stream must be in bytes for a nicer error message.

**Comment by isagalaev** [comment]
Yes, the requirement for the stream to be bytes is not documented anywhere, sorry :-( The intention is to open network streams anyway which are bytes by default. If you could make a patch with a better error message I'd happily merge it!

**Comment by acrisci** [comment]
There are a few ways to do that.

You could check that the stream is bytes before trying to parse, but then that might break some python2 applications.

You could check for the exception when you read.

You could try to do the conversion implicitly for python3.

You could just do a documentation update.
