### ISSUE TITLE
Control buffer size

### ISSUE THREAD

**Issue by acrisci** [isagalaev/ijson#31]
I have an application that reads a continuous stream of json data from a process as an infinite array. I need to read an object out of this array about once per second. Each object is about 200 characters long.

The current buffer size is 16 * 1024. This means that I don't get events until the buffer is full, which takes a very long time. I need to make the buffer size very small for my application to work correctly.

I would like to add a kwarg to `ijson.parse()` to control the buffer size.

**Comment by pwalsh** [comment]
+1

**Comment by isagalaev** [comment]
That is a very interesting usecase indeed. Could you make a patch for this? Should be pretty straightforward…

**Comment by acrisci** [comment]
Looking through the code, I found I could already do this with the yajl backend.

**Comment by acrisci** [comment]
@jmarshall9120 [here](https://github.com/acrisci/i3-dstatus/blob/master/i3dstatus/generators/other-statuslines) is the use case I was referring to in the issue.
