### ISSUE TITLE
Ability to iteratively parse a json array

### ISSUE THREAD

**Issue by fizyk** [isagalaev/ijson#33]
I've got this kind of list:

``` json
[{"feed": {"map": 2}}, {"feed": "alert"}]
```

And I'd  like to iteratively parse out two objects:
`{"feed": {"map": 2}}` and `{"feed": "alert"}` right now unfortunately I'll get full json parsed if I'll use ijson.items

**Comment by isagalaev** [comment]
The empty prefix in `items(f, '')` means the root object which is your entire array. If you want individual items of the array, add the special word "item" to the path: `items(f, 'item')`. This works for all arrays on any level of hierarchy.

**Comment by fizyk** [comment]
thanks!
