### ISSUE TITLE
valid floats cause UnexpectedSymbol exceptions

### ISSUE THREAD

**Issue by tedx** [isagalaev/ijson#34]
Floats like 5e-07 which I beleive is a valid value cause UnexpectedSymbol exceptions. 5.0e-07 doesn't have the same problem.

**Comment by isagalaev** [comment]
I can't reproduce it with the current code using either python or yajl2 backends. Which version are you using?

**Comment by isagalaev** [comment]
Here:

```
In [1]: import ijson.backends.python as ijson

In [2]: from io import BytesIO

In [3]: list(ijson.parse(BytesIO(b'5e-07')))
Out[3]: [('', 'number', Decimal('5E-7'))]
```

**Comment by tedx** [comment]
Yes I had an older version I updated and no longer see the issue, thanks.

**Comment by isagalaev** [comment]
Great!
