### ISSUE TITLE
2.2 release from pip doesn't handle cffi backends

### ISSUE THREAD

**Issue by athoune** [isagalaev/ijson#44]
It works with ```pip install --upgrade git+https://github.com/isagalaev/ijson.git ```

Please, can you release and push a new version to pypi?

**Comment by tgalery** [comment]
yep that would be nice

**Comment by haizaar** [comment]
+1 for that! Please release.

**Comment by isagalaev** [comment]
Released 2.3 with CFFI to PyPI. Sorry for taking so long!
