### ISSUE TITLE
NEED SPEED UP. It is good but slow.  

### ISSUE THREAD

**Issue by fivejjs** [isagalaev/ijson#47]
Hi, 

Is it possible speed up it with concurrent processing.

**Comment by isagalaev** [comment]
Did you try the CFFI backend?

As for concurrency, it's tricky in Python because of the GIL. And with multiple processes you'll loose much more on IPC than you gain from parallelizing.

**Comment by fivejjs** [comment]
I will try CFFI then. Thanks,
