### ISSUE TITLE
Use new style CFFI callbacks in CFFI backend

### ISSUE THREAD

**Issue by thedrow** [isagalaev/ijson#50]
See http://cffi.readthedocs.io/en/latest/using.html#extern-python-new-style-callbacks

**Comment by rtobar** [comment]
I have an initial set of changes in a local repo that implement this, but not in a publishable form yet. Performance-wise this doesn't bring much benefit at the moment though compared with other parts of the code, and it of course imposes the requirement of a compiler during installation (which could be checked in setup.py).

**Comment by isagalaev** [comment]
Looks like this is fixed by #56.
