### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by guyskk** [isagalaev/ijson#51]
Hi, I am writing [validater](https://github.com/guyskk/validater), which is based on ijson, but I found that
ijson's performance is poor, expecially deep list: `'[' * 8000 + ']' * 8000`.
here is my test result, it is much slower than standard json:

```
[guyskk@localhost validater]$ python benchmark.py 
------------------------ijson python------------------------
normal data: 0.040082 sec
deep data: 24.490807 sec
----------------------ijson yajl2_cffi----------------------
normal data: 0.029769 sec
deep data: 24.238428 sec
-------------------------validater--------------------------
normal data: 0.061465 sec
deep data: 0.034018 sec
-----------------------standard json------------------------
normal data: 0.004895 sec
deep data: 0.065272 sec
[guyskk@localhost validater]$ python --version
Python 3.5.1
[guyskk@localhost validater]$ 
```

[benchmark](https://github.com/guyskk/validater/blob/master/benchmark.py)  and usage:
```
git clone https://github.com/guyskk/validater
cd validater
pip install -e .
python benchmark.py
```

**Comment by naringas** [comment]
try using the cfffi backend
```
from ijson.backends.python import basic_parse
```
https://github.com/guyskk/validater/blob/master/validater/schema.py#L8

try with 
```
from ijson.backends.yajl2_cffi import basic_parse
```

but you will need to install some things in your environment.
