### ISSUE TITLE
cannot parse integer written in format 1.55E10

### ISSUE THREAD

**Issue by diahnuri** [isagalaev/ijson#59]
Dear Sir,,
I have a large json, the size is around 1,5GB.  One item in json is price of property which written in format e.g. 1.55E10, 6.5E10, etc. When I parse with IJSON, the error like this 'Unexpected symbol "E" at 377'.
Temporary solution is I must replace this integer format into 1.55e+10, but It's so hard to replace all parts in large JSON. Please help me. Any help would be appreciated.

**Comment by akaIDIOT** [comment]
Do you have an example of this? The following seems to work for me:

~~~~
>>> data = StringIO('{"key": 1.55E10}')
>>> list(ijson.parse(data))
[('', 'start_map', None),
 ('', 'map_key', 'key'),
 ('key', 'number', 15500000000),
 ('', 'end_map', None)]

>>> data = StringIO('{"key": 6.5E10}')
>>> list(ijson.parse(data))
[('', 'start_map', None),
 ('', 'map_key', 'key'),
 ('key', 'number', 65000000000),
 ('', 'end_map', None)]
~~~~
