### ISSUE TITLE
Publish current master to PyPI

### ISSUE THREAD

**Issue by akaIDIOT** [isagalaev/ijson#63]
Current release on PyPI is a bit behind on the current master on github. The latest commit being one I personally care about, I'd love to see the current state on PyPI. As the int/float parsy thing was a bug for my env, I find myself building the current master and distributing that build to people running into it or still monkey-patching a fix into code.

Can the current state of things be released to PyPI or is there something blocking that?

**Comment by HarkonenBade** [comment]
+1 for this request.

**Comment by rtobar** [comment]
A new release in on PyPI

**Comment by akaIDIOT** [comment]
Thnx for pointing that out, just checked to see that it includes the fix I was looking for :)
