### ISSUE TITLE
add more documentation to the package

### ISSUE THREAD

**Issue by franklingu** [isagalaev/ijson#64]
Hi, I am doing some research and find this package, this it is really helpful for parsing my very large json files. The only thing is that the documentation is not sufficient at all and maybe adding docs would help a lot for this package to get more attention:

[This SO answer](https://stackoverflow.com/a/17326199) actually provides some brief but useful documentation already

**Comment by isagalaev** [comment]
The project has moved over to a new maintainer: https://github.com/rtobar/ijson. Please reopen this issue there if it's still relevant.
