### ISSUE TITLE
'FFI' object has no attribute 'new_handle'

### ISSUE THREAD

**Issue by tedx** [isagalaev/ijson#65]
I was trying to use the yajl2_cffi backend on a system without a compiler installed and I get an exception:
'FFI' object has no attribute 'new_handle'

Is this the expected behavior? Is a compiler required for this to work?

Ted

**Comment by isagalaev** [comment]
The project has moved over to a new maintainer: https://github.com/rtobar/ijson. Please reopen this issue there if it's still relevant.
