### ISSUE TITLE
Multiple file opens required for multiple iterators on same JSON

### ISSUE THREAD

**Issue by ericbarnhill** [isagalaev/ijson#70]
Something that might be clarified in the documentation:

While IJSON returns a generator of a specific item within the JSON, stepping through the generator steps through all items, affecting any additional iterators. Example:

    f = open(filepath, 'r')
        g1 = ijson.items(f, Category1)
        g2 = ijson.items(f, Category2)
    [...]
    f.close()

If i call g1.next() within [...], it will yield the first Category1 item. If I then call g2.next(), it will yield the _second_ Category2 item.

I can work around this by using different file opens:

    f1= open(filepath, 'r')
    f2 = open(filepath, 'r')
        g1 = ijson.items(f1, Category1)
        g2 = ijson.items(f2, Category2)
    [...]
    f1.close()
    f2.close()

**Comment by SalomonSmeke** [comment]
Not quite sure that this belongs in the documentation for iJson, all buffers are consumed on read, this is just how buffers work. You could _optionally_ reset the seek after each event, and then seek back to the seek position at the start of each event. But that would be really slow and make little sense.

Basically, you are correct that this would require multiple file opens. But I don't think that belongs in documentation as it has nothing to do with iJson, rather with how python buffers work.
