### ISSUE TITLE
A bug when setting multiple_values=True

### ISSUE THREAD

**Issue by bmizhen-exos** [isagalaev/ijson#75]
Hello, I am trying to parse a stream that contains multiple json objects, one after another, not one per line.

I am doing this:
```python
    import ijson.backends.yajl2_cffi as ijson

    for i in ijson.common.items(ijson.parse(input_stream, multiple_values=True), json_prefix):
        print(i)
```

Getting the following exception:
```
  File "/.direnv/python-3.7.2/lib/python3.7/site-packages/ijson/common.py", line 138, in items
    current, event, value = next(prefixed_events)
  File "/.direnv/python-3.7.2/lib/python3.7/site-packages/ijson/common.py", line 65, in parse
    for event, value in basic_events:
  File "/.direnv/python-3.7.2/lib/python3.7/site-packages/ijson/backends/yajl2_cffi.py", line 213, in basic_parse
    handle = yajl_init(scope, events, **config)
  File "/.direnv/python-3.7.2/lib/python3.7/site-packages/ijson/backends/yajl2_cffi.py", line 172, in yajl_init
    yajl.yajl_config(handle, YAJL_MULTIPLE_VALUES, 1)
TypeError: argument 3 passed in the variadic part needs to be a cdata object (got int)
```

This looks to me  like an int is being passed where underlying c library expects a cdata object.
Is this a bug? 
And a separate question am I using the library correctly for reading a stream of json objects?

Thank you!

**Comment by bmizhen-exos** [comment]
Wrapping the third arg in ffi.new(1) solved the problem.
I will send a pull request

```python
def yajl_init(scope, events, allow_comments=False, multiple_values=False):
    scope.ctx = ffi.new_handle(events)
    scope.callbacks = ffi.new('yajl_callbacks*', _callback_data)
    handle = yajl.yajl_alloc(scope.callbacks, ffi.NULL, scope.ctx)

    if allow_comments:
        yajl.yajl_config(handle, YAJL_ALLOW_COMMENTS, ffi.new(1))
    if multiple_values:
        yajl.yajl_config(handle, YAJL_MULTIPLE_VALUES, ffi.new(1))
```

**Comment by bmizhen-exos** [comment]
Hmm, I found that the fix is already there
https://github.com/isagalaev/ijson/blob/master/ijson/backends/yajl2_cffi.py#L172
But it's not in my code. Maybe it needs to be released?

**Comment by SalomonSmeke** [comment]
though the actual solution is for the latest version to be put on PyPi

`-e git://github.com/isagalaev/ijson.git@e252a50db34b71cc2b5e0b9a77cd76dee8e95005#egg=ijson # module: ijson;`

should do ya fine in requirements.txt

and for just pip install:

`pip install git+https://github.com/tangentlabs/isagalaev/ijson.git@e252a50db34b71cc2b5e0b9a77cd76dee8e95005`

**Comment by rtobar** [comment]
A new version with the fix has been uploaded to PyPI.

**Comment by bmizhen-exos** [comment]
Thank you!
