### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by clokep** [isagalaev/ijson#77]
Hi! I see there's been a couple of new releases of this, which is awesome. Thanks!

It'd be great to know what has changed between versions to see how risky an upgrade is. I didn't see a changelog anywhere in the repository and it would be great if there was one! 👍 

Thanks again!

**Comment by rtobar** [comment]
The code is now kept at ICRAR/ijson, there is a changelog there

**Comment by clokep** [comment]
Oops. Got my repos confused. Thanks for responding! 👍
