### ISSUE TITLE
Releases missing on GitHub

### ISSUE THREAD

**Issue by jayvdb** [isagalaev/ijson#79]
https://pypi.org/project/ijson/ has 2.5.x , which the releases tab here only has 2.3

**Comment by jayvdb** [comment]
@rtobar , I see you are taking on maintenance. Great to see.  Can you confirm that 2.4/2.5 were "non code changing" releases?

**Comment by rtobar** [comment]
Hi @jayvdb, there is a changelog under ICRAR/ijson that describes changes, please refer to that.

**Comment by jayvdb** [comment]
Lovely.  Sorry, I see PyPI is pointing at it.  Somehow I missed that.
